USE backup_datn;

CREATE TABLE file (
  State INT DEFAULT NULL,
  FileID INT NOT NULL AUTO_INCREMENT,
  FileName VARCHAR(255) NOT NULL,
  OrganizationUnitID INT DEFAULT NULL,
  OrganizationUnitName VARCHAR(255) DEFAULT NULL,
  ParentID INT DEFAULT NULL,
  CreatedBy INT DEFAULT NULL,
  CreatedDate DATETIME NOT NULL,
  SharedIDs INT DEFAULT NULL,
  SharedNames VARCHAR(255) DEFAULT NULL,
  SharedDate DATETIME DEFAULT NULL,
  Note TEXT DEFAULT NULL,
  NoteShared TEXT DEFAULT NULL,
  NoteOrganizationUnit TEXT DEFAULT NULL,
  TypeFile VARCHAR(50) DEFAULT NULL,
  Path VARCHAR(255) DEFAULT NULL,
  Content TEXT DEFAULT NULL,
  TenantID CHAR(36) DEFAULT NULL,
  Size INT DEFAULT NULL,
  TypeFileEnum INT DEFAULT NULL,
  PRIMARY KEY (FileID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 170,
AVG_ROW_LENGTH = 17694,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE employee (
  EmployeeID INT NOT NULL AUTO_INCREMENT,
  EmployeeName VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Phone VARCHAR(20) DEFAULT NULL,
  OrganizationUnitID INT DEFAULT NULL,
  OrganizationUnitName VARCHAR(255) DEFAULT NULL,
  TenantID CHAR(36) DEFAULT NULL,
  EmployeeCode VARCHAR(50) DEFAULT NULL,
  BirthDay DATETIME DEFAULT NULL,
  Gender VARCHAR(10) DEFAULT NULL,
  Avatar VARCHAR(255) DEFAULT NULL,
  JobPositionID INT DEFAULT NULL,
  JobPositionName VARCHAR(100) DEFAULT NULL,
  Status INT DEFAULT NULL,
  PRIMARY KEY (EmployeeID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 18,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE organization_unit (
  State INT DEFAULT NULL,
  OrganizationUnitID INT NOT NULL AUTO_INCREMENT,
  OrganizationUnitName VARCHAR(255) NOT NULL,
  ParentID INT DEFAULT NULL,
  Code VARCHAR(50) DEFAULT NULL,
  Address TEXT DEFAULT NULL,
  Status INT DEFAULT NULL,
  Note TEXT DEFAULT NULL,
  TenantID CHAR(36) DEFAULT NULL,
  PRIMARY KEY (OrganizationUnitID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 11,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE role (
  RoleID INT NOT NULL AUTO_INCREMENT,
  RoleCode VARCHAR(50) DEFAULT NULL,
  RoleName VARCHAR(255) NOT NULL,
  Note TEXT DEFAULT NULL,
  TenantID CHAR(36) DEFAULT NULL,
  PRIMARY KEY (RoleID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 31,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE role_detail (
  RoleDetailID INT NOT NULL AUTO_INCREMENT,
  RoleID INT DEFAULT NULL,
  SubCode VARCHAR(50) DEFAULT NULL,
  SubName VARCHAR(255) DEFAULT NULL,
  Action VARCHAR(50) DEFAULT NULL,
  ActionName VARCHAR(255) DEFAULT NULL,
  Value TINYINT(1) NOT NULL,
  TenantID CHAR(36) DEFAULT NULL,
  PRIMARY KEY (RoleDetailID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10032,
AVG_ROW_LENGTH = 146,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE user (
  UserID CHAR(36) NOT NULL,
  EmployeeID INT DEFAULT NULL,
  EmployeeName VARCHAR(255) DEFAULT NULL,
  Email VARCHAR(255) DEFAULT NULL,
  Phone VARCHAR(20) DEFAULT NULL,
  Password VARCHAR(255) DEFAULT NULL,
  RoleID INT DEFAULT NULL,
  RoleName VARCHAR(255) DEFAULT NULL,
  OrganizationUnitID INT DEFAULT NULL,
  OrganizationUnitName VARCHAR(255) DEFAULT NULL,
  TenantID CHAR(36) DEFAULT NULL,
  PRIMARY KEY (UserID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;